apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pointsbet-test-app
  namespace: argocd
spec:
  destination:
    namespace: test-ns
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest
    repoURL: 'https://github.com/yashjain10038/argo-basics.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
